### ISSUE TITLE
Project usage example

### ISSUE THREAD

**Issue by SandoDev** [bharel/mkdocs-render-swagger-plugin#13]
Does anyone have a simple project already built that is using this plugin?
It is not clear what to do, or where to put the swagger.json, or what the rendering would look like.

I have this swagger.json how do i render it with mkdocs? https://petstore.swagger.io/v2/swagger.json

**Comment by bharel** [comment]
Try putting it in the same folder as the `.md` file. Then reference it in the file as written in the instructions.

**Comment by juniorschen** [comment]
@bharel  
But what if I don't want to do this for a physical file on disk, I can't use "https://petstore.swagger.io/v2/swagger.json" as the json path? In this case the plugin makes the request to get the JSON

**Comment by juniorschen** [comment]
@bharel  what could be wrong?
![image](https://user-images.githubusercontent.com/46031261/121076759-280ad400-c7ad-11eb-8c6a-1d3c65c123f5.png)
![image](https://user-images.githubusercontent.com/46031261/121076785-2fca7880-c7ad-11eb-87f9-81d266f30bc2.png)
![image](https://user-images.githubusercontent.com/46031261/121076719-19bcb800-c7ad-11eb-9c8d-0f12b57da7f2.png)

**Comment by bharel** [comment]
@juniorschen This feature was recently added in #11 , I shall publish a new release in the upcoming days.

**Comment by bharel** [comment]
@SandoDev @juniorschen Version 0.0.3 was released. Please update me if you're happy with the way it works 😄

**Comment by SandoDev** [comment]
I will close this issue!
but this project did not work for me even after following all the instructions.

I tried the new update and it still didn't work for me.

## Tools
* Python 3.6.9
* mkdocs==1.2.1
* mkdocs-render-swagger-plugin==0.0.3

## Screenshots
* Working directory
![image](https://user-images.githubusercontent.com/46248182/121965659-f9ec3d80-cd32-11eb-82b0-c38ad5e42c59.png)

* mkdocs.yml
![image](https://user-images.githubusercontent.com/46248182/121965734-18523900-cd33-11eb-96f9-b46847ec9836.png)

* index.md
![image](https://user-images.githubusercontent.com/46248182/121965831-43d52380-cd33-11eb-969b-eb8391b447bb.png)

* test.md
![image](https://user-images.githubusercontent.com/46248182/121965845-4afc3180-cd33-11eb-84c3-5aa418db292a.png)

* result of index.md
![image](https://user-images.githubusercontent.com/46248182/121966022-8dbe0980-cd33-11eb-95e5-3d6ef76cda53.png)

* result of test.md
![image](https://user-images.githubusercontent.com/46248182/121966052-96aedb00-cd33-11eb-9b7a-9fd950bc318b.png)

**Comment by bharel** [comment]
@SandoDev you shouldn't add the brackets (`<>`). It's just a placeholder.
