### ISSUE TITLE
Use multiple swagger.json files in the same page

### ISSUE THREAD

**Issue by Thibaudkhan** [bharel/mkdocs-render-swagger-plugin#18]
**Hello**,

I cannot use 2 json Files in the same page.md
Did I do something wrong ?

**Comment by blueswen** [comment]
@Thibaudkhan  I created another MkDocs plugin to render Swagger UI https://github.com/blueswen/mkdocs-swagger-ui-tag. Which could render multiple Swagger UI in same page with different OpenAPI Spec file and supports build-in multiple OAS in single Swagger UI with top bar selector. Maybe my plugin could fit your requirement.

**Comment by bharel** [comment]
Shouldn't be an issue. What have you tried?

**Comment by ChrisChinchilla** [comment]
I have the same question and kind of prefer this plugin as it doesn't use iFrames, but @bharel how do you support it? I tried adding the tag twice and only the last spec is displayed

**Comment by bharel** [comment]
Need to check if https://github.com/bharel/mkdocs-render-swagger-plugin/pull/26  fixed. Might have been an issue with the IDs.

**Comment by bharel** [comment]
Yeah, #26 have fixed it.
@Thibaudkhan  @ChrisChinchilla please check with latest version on master, will soon deploy for 0.1.1
