### ISSUE TITLE
Swagger file in relative path

### ISSUE THREAD

**Issue by miquelis** [bharel/mkdocs-render-swagger-plugin#19]
I am having difficulty adding the Swagger file when it is in another directory. The plugin only recognizes the file when it is in the same directory as the file.md

Example of my structure

```
project
│   test.md
│
└───assets
│   │   └───swagger
│   │       |  openapi.json

```

![image](https://user-images.githubusercontent.com/13782306/170801025-31a54e03-8405-4a61-b057-d59ec0caf5fb.png)

Attempts to add openapi.json:

- `./assets/swagger/openapi.json`
- `/assets/swagger/openapi.json`
- `assets/swagger/openapi.json`

**Comment by blueswen** [comment]
@miquelis I created another MkDocs plugin to render Swagger UI https://github.com/blueswen/mkdocs-swagger-ui-tag. Which could include OpenAPI Spec file cross directories like include image in MkDocs. Maybe my plugin could fit your requirement.

**Comment by bharel** [comment]
As written in the docs:

> Place an OpenAPI json file in the same folder as the .md file.

That's actually a security feature, to prevent LFI/RFI attacks. We don't want someone to write `../../../../etc/passwd` would we 😉 

While we have the `!!swagger-http!!` to compensate, adding a config option to disable the security and allow accessing arbitrary files might be an option.

**Comment by dazinator** [comment]
@bharel the way dotnet webserver handles this is that by default it won't serve past the "base" directory. So for example, for mkdocs this would be the same as not allowing navigation beyond the folder with mkdocs file in it. So if your ".md" file was a in a subdirectory, relative paths to other subdirectories woould be fine so long as the navigation depth wasn't beyond the base directory with mkdocs file.

**Comment by bharel** [comment]
We can add that as a separate feature

**Comment by bharel** [comment]
Let's try it. I now allow it using a configuration option.
