### ISSUE TITLE
Actual Examples

### ISSUE THREAD

**Issue by Andre601** [bharel/mkdocs-render-swagger-plugin#22]
It's hard to visualize how the stuff would look like (And where and how the file for OpenAPI should be placed), so adding some actual examples, maybe even with a live preview using gh-pages, would certainly not be a bad idea here.

I myself considered to try and use this plugin, but I don't want to "buy the cat in the sack" here, as I don't know how it would look like and if it was somewhat compatible with the theme I use (Material for MkDocs). Not to mention what possible styling options are, as I myself already have a API documentation inspired by OpenAPI and would love to keep a similar style (Especially the Icons)

So, if possible, some examples and a live-preview should be implemented to allow an easier understanding of what the plugin may produce.

**Comment by bharel** [comment]
Good idea. Does anyone mind taking a screenshot?

**Comment by aviaviavi** [comment]
My team currently uses this plugin with live API docs here which can serve as an example: https://docs.scarf.sh/api-v2/. Hope that helps, thanks for developing this @bharel!

**Comment by bharel** [comment]
@aviaviavi

Oh awesome! Thanks for letting me know :-)
Do you mind me adding it to the front page (readme)?

**Comment by aviaviavi** [comment]
@bharel apologies missed this message in my notifications. Not all, go for it!

**Comment by bharel** [comment]
Added to the front page. Thank you!
