### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by bharel** [bharel/mkdocs-render-swagger-plugin#3]

**Comment by iamansoni** [comment]
I would like to work on this task. You can assign it to me.

**Comment by bharel** [comment]
@iamansoni sounds great, keep in mind that the plugin is at it's first version, 0.0.1, and the repository was just created.
The only thing I'm afraid of is that things might change quickly.

**Comment by iamansoni** [comment]
@bharel don't you worry, you will easily be able to showcase that under the "CHANGELOG" section in the future!
I wanted to know that if this plugin is using any official plugins or extensions that mkdock supports; in order to add their description in the readme.md.

**Comment by bharel** [comment]
The plugin does not use other plugins or extensions besides MKDocs' official plugin API and swagger's official API.
